# Generated by Django 2.1.5 on 2019-02-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='repos',
            field=models.CharField(default='empty', max_length=500),
            preserve_default=False,
        ),
    ]
