# Generated by Django 2.1.5 on 2019-02-17 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_repos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='repos',
        ),
    ]
